# Welcome to Jekyll!
# About Theme
#
# Yet another theme for elegant writers with modern flat style and beautiful
# night/dark mode.
#
# Website: https://github.com/jeffreytse/jekyll-theme-yat
#
# You can do anything you want, including projects for your clients, as long
# as you mention an attribution back (credit links in footer or project).
# See the LICENCE file.
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you
# use 'bundle exec jekyll serve'. If you change this file, please restart
# the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "jnooree.github.io"
email: "jnooree@snu.ac.kr"
author: "Nuri Jung"
sns:
  - link: https://github.com/jnooree
    icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32.58 31.77" style="height:20px; vertical-align:text-bottom;"><style>:root {--color: #231e1b;} html[data-theme="dark"] {--color: #fff;} path {fill: var(--color);fill-rule: evenodd;}</style><path d="M16.29,0a16.29,16.29,0,0,0-5.15,31.75c.82.15,1.11-.36,1.11-.79s0-1.41,0-2.77C7.7,29.18,6.74,26,6.74,26a4.36,4.36,0,0,0-1.81-2.39c-1.47-1,.12-1,.12-1a3.43,3.43,0,0,1,2.49,1.68,3.48,3.48,0,0,0,4.74,1.36,3.46,3.46,0,0,1,1-2.18c-3.62-.41-7.42-1.81-7.42-8a6.3,6.3,0,0,1,1.67-4.37,5.94,5.94,0,0,1,.16-4.31s1.37-.44,4.48,1.67a15.41,15.41,0,0,1,8.16,0c3.11-2.11,4.47-1.67,4.47-1.67A5.91,5.91,0,0,1,25,11.07a6.3,6.3,0,0,1,1.67,4.37c0,6.26-3.81,7.63-7.44,8a3.85,3.85,0,0,1,1.11,3c0,2.18,0,3.94,0,4.47s.29.94,1.12.78A16.29,16.29,0,0,0,16.29,0Z" /></svg>'
  - link: https://facebook.com/Chem.JNR
    icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" style="height:20px;vertical-align:text-bottom;"><defs><style>.cls-1{fill:#1877f2;}.cls-2{fill:#fff;}</style></defs><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M1024,512C1024,229.23,794.77,0,512,0S0,229.23,0,512c0,255.55,187.23,467.37,432,505.78V660H302V512H432V399.2C432,270.88,508.44,200,625.39,200c56,0,114.61,10,114.61,10V336H675.44c-63.6,0-83.44,39.47-83.44,80v96H734L711.3,660H592v357.78C836.77,979.37,1024,767.55,1024,512Z"/><path class="cls-2" d="M711.3,660,734,512H592V416c0-40.49,19.84-80,83.44-80H740V210s-58.59-10-114.61-10C508.44,200,432,270.88,432,399.2V512H302V660H432v357.78a517.58,517.58,0,0,0,160,0V660Z"/></g></g></svg>'
  - link: https://instagram.com/__nuri_jung_
    icon: '<img style="height:20px;vertical-align:text-bottom;" src="/assets/images/ig-icon.png">'

# Copyright setting
# You can use any html code, currently below placeholders are available:
# * current year: {currentYear}
# * author: {author} (Value is the same as site.author)
# * copyright: (c) - ©
# * copyleft: (cleft)
# * sound recording copyright: (p) - ℗
#
# For example:
#   "Copyright (c) 2017-{currentYear} <a href="https://example.com">{author}</a>"
#   "Copyright © 2017-2021 Foobar"
#
copyright: 'Copyright (c) 2022-{currentYear} {author}, licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0 International</a>. <span class="tie"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="/assets/images/cc.svg"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="/assets/images/by.svg"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="/assets/images/nc.svg"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="/assets/images/sa.svg"></span></p>'

description: >- # this means to ignore newlines until "baseurl:"
  Nuri Jung's dev blog!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jnooree.github.io" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "" # the favicon for your site

# Yat date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
yat:
  date_format: "%F %r"
last-modified-at:
  date-format: "%F %r"

# If you want more debug log, you can set true
# debug: false

# If you don't want transparent header, you can set false
# header_transparent: true

# If you want to change the content width, you can set to another value
# content_width: "920px"

# Google analytics
# google_analytics: [Tracking ID]

# If you want to generate website sitemap, you can set true
sitemap: true

# If you want to change site language, you can set lang option
lang: "ko"
timezone: Asia/Seoul

# Translate languges
# langs refer to https://cloud.google.com/translate/docs/languages
# translate_langs:
#   - lang: en
#     img: https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png
#     text: English
#
#   - lang: fr
#     img: https://cdn.countryflags.com/thumbs/france/flag-400.png
#     text: French
#
#   - lang: zh-CN
#     img: https://cdn.countryflags.com/thumbs/china/flag-400.png
#     text: Chinese(Simple)
#
#   - lang: ja
#     img: https://cdn.countryflags.com/thumbs/japan/flag-400.png
#     text: Japanese
#
#   - lang: ko
#     img: https://cdn.countryflags.com/thumbs/south-korea/flag-400.png
#     text: Korean
#
#   - lang: ru
#     img: https://cdn.countryflags.com/thumbs/russia/flag-400.png
#     text: Russian

# You can choose a theme color
# Default theme colors as below:
# coolblack: #090a0b
# spacegrey: #353535
# snowwhite: #ffffff
#
# theme_color: snowwhite
#
# Custom color as below:
# theme_color: "#882250"

# You can choose a brand color
# Default brand colors as below:
# orangered: #ff5100
# greatgold: #f2cb05
# greenblue: #389092
#
# brand_color: orangered
#
# Custom color as below:
# brand_color: "#1a8e42"

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is"manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
#
# night_mode: "auto"

# Code badge setting
# You can enable or disable the code badge and so on
# code_badge:
#   enabled: "true"
#   color: "#fff"
#   background_color: "#ff4e00"
#   text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.md
  - archives.md
  - categories.md
  - tags.md
  - about.md
  - source.md

# Page default value
# defaults:

# Banner default settings
# These banner settings are for global banner default, but you can also
# config it by the front matter for one specific post
# banner:
#   height: "200px"         # Banner default height
#   opacity: 0.5            # Banner opacity (100% is 1.0)
#   video: null             # Video banner source
#   loop: true              # Video loop
#   volume: 0               # Video volume (100% is 1.0)
#   image: null             # Image banner source
#   start_at: 0             # Video start time
#   background: "rgba(0, 0, 0, 0.8)"  # Banner background (Could be a image)
#   min_height: null        # Banner minium height
#   heading_style: null     # Custom heading style (e.g. "font-weight: bold; text-decoration: underline")
#   subheading_style: null  # Custom subheading style (e.g. color: gold)

# Excerpt size setting
# excerpt_size: 350

# Pagination setting
paginate: 10

# Disqus comments
disqus:
  shortname: jnooree-dev

# Gitment comments
# gitment:
#   username:
#   repo:
#   client_id:
#   client_secret:

# Build settings
theme: "jekyll-theme-yat"
# highlighter: none
# markdown: kramdown
# kmarkdown:
#   input: GFM
plugins:
  - jekyll-last-modified-at
  - jekyll-redirect-from
  - jekyll-include-cache
