name: Github Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/scripts/tweet.py
      - .github/workflows/tweet-new-posts.yml

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - run: .github/scripts/build_jekyll.sh
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
