name: tweet-release

on:
  page_build

defaults:
  run:
    shell: bash

jobs:
  get-new-files:
    if: "!github.event.repository.private"
    outputs:
      new-files: ${{ steps.changed-files.added_files }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 2

      - name: Get changed files list
        id: changed-files
        uses: tj-actions/changed-files@v27
        with:
          files: '**/*.html'

  tweet:
    needs: get-new-files
    if: "needs.get-new-files.outputs.new-files != ''"
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v4

      - name: Install tweepy
        run: python -m pip install -U tweepy pyyaml

      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Tweet new files
        run: |
          python .github/scripts/tweet.py ${{ needs.get-new-files.outputs.new-files }}
        env:
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
